<?php


function week5_menu() {
    
    $items = array();
    $items['week5'] = array(
       'title'           => 'Week5',
       'access callback' => TRUE,
       'page callback'   => 'week5_start',
    );

    return $items;

}


function week5_start() {
    return drupal_get_form('week5_form');
}


function week5_form($form,&$form_state) {

    $form = array();

    // name field
    $form['name'] = array (
        '#type'        => 'textfield',
        '#title'       => t('What\'s your name?'),
        '#description' => t('Enter your name already!'),
        '#required'    => TRUE,
    );

    // gender field
    $gender = array();
    $gender['m'] = t('Male');
    $gender['f'] = t('Female');

    $form['gender'] = array(
        '#type'    => 'radios',
        '#title'   => t('What is your gender?'),
        '#options' => $gender,
    );
    
    // specialization field
    $specializations = array(
        'arm'      => t('Archives and Record Management'),
        'hci'      => t('Human Computer Interaction'),
        'iar'      => t('Information Analysis and Retrieval'),
        'iem'      => t('Information Economics for Management'),
        'lis'      => t('Library and Information Science'),
        'pi'       => t('Preservation of Information'),
        'slm'      => t('School Library Media'),
        'sc'       => t('Social Computing'),
        'tailored' => t('Tailored'),
    );
    
    // save the values so we can use them in the submit handler
    variable_set('specializations', $specializations);  
      
    $form['specialization'] = array(
        '#type'        => 'select',
        '#title'       => t('What are you specializing in?'),
        '#description' => t('Choose all you are working on.'),
        '#required'    => TRUE,
        '#multiple'    => TRUE,
        '#options'     => $specializations,
    );
    
    // graudation date field
    $grad_dates = drupal_map_assoc(array(
        t('Never'),
        t('2012'),
        t('2013'),
        t('2014'),
        t('2015'),
        t('2016'),
        t('2017'),
    ));
    
    $form['grad_date'] = array(
        '#type'    => 'select',
        '#title'   => t('When do you expect to graduate?'),
        '#options' => $grad_dates,
    );
    
    // class survey
    $classes = drupal_map_assoc(array(
        t('SI500'),
        t('SI501'),
        t('SI502'),
        t('SI522'),
        t('SI523'),
        t('SI549'),
    ));
    
    $form['classes'] = array(
        '#type' => 'checkboxes',
        '#title' => t('What classes have you taken?'),
        '#options' => $classes,
    );
    
      
    // study description
    $form['description'] = array(
        '#type'        => 'textarea',
        '#title'       => t('Describe your study'),
        '#description' => t('Tell us what you like (or don\'t like) about it.'),
        '#rows'        => '5',
        '#cols'        => '45', 
    );


    // email address
    $form['email'] = array(
        '#type'        => 'textfield',
        '#title'       => t('Enter your email address so we can contact you.'),
        '#description' => t('Or don\'t if you want to be left alone.'),
    );
    
    // url
    $form['url'] = array(
        '#type'        => 'textfield',
        '#title'       => t('Do you have a website?'),
        '#description' => t('Enter the URL here and we\'ll check it out.'),
    );
   
    // submit the puppy
    $form['submit'] = array(
        '#type'  =>'submit',
        '#value' =>'Submit',
    );
    
    return $form;
}

function week5_form_validate($form, &$form_state) {

    // make sure the name entered isn't my grandfathers :-).
    if ($form_state['values']['name'] == 'Edward Sopcak') {
        form_set_error('name', t('That was my grandfathers name, you can\'t have it! Choose another.'));
    }
    
    // chide the user for chosing Never for graduation date.
    if ($form_state['values']['grad_date'] == 'Never') {
        form_set_error('grad_date', t('Never graduating?? Come on now, be optimistic'));
    }
    
    // if user entered an email addr, make sure it's valid
    if ($form_state['values']['email'] != '' && !valid_email_address($form_state['values']['email'])) {
        form_set_error('email', t('Please enter a valid email address in that field if you put anything'));
    }
    
    // if the user entered a URL, make sure it's valid
    if ($form_state['values']['url'] != '' && !valid_url($form_state['values']['url'])) {
        form_set_error('url', t('Please enter a valid URL in that field if you\'re gonna enter something'));
    }

}

function week5_form_submit($form, &$form_state) {

    // pull form data
    $name = check_plain($form_state['values']['name']);
    
    // I don't check_plain these. They are just indexes 
    $specialization_choices = $form_state['values']['specialization'];
        
    $grad_date = check_plain($form_state['values']['grad_date']);
    
    
    // construct tweet & email
    
    // pull the specialization list
    $specializations = variable_get('specializations');
    
    // yank out the "readable" translated text for each
    $specialization_choices_count = count($specialization_choices);
    $specialization_text = '';
    foreach ($specialization_choices as $specialization_index) {   
        $specialization_text .= "$specializations[$specialization_index], ";
    }

    $mesg = "Yo $name. I see you are in $specialization_choices_count specialization(s): $specialization_text. Gonna graduate in $grad_date, huh? Cool.";
    
    // limit string to 140 chars for twitter.
    $twitter_mesg = substr($mesg, 0, 140);
    //si635helper_twitter($twitter_mesg);
    my_twitter_helper_send($twitter_mesg);
    
    // email the full message
    mail("brenmh@umich.edu",'A post from Week5', $mesg);
} 