<?php

function week4_menu()
{
    $items = array();

    $items['week4'] = array(
        'title' => 'Week4',
        'page callback' => 'week4_do',
        'access callback' => 'user_access',
        'access arguments' => array('admin week4'),
    );
    
    $items['week4/link'] = array(
        'title' => 'Week4 Link',
        'page callback' => 'week4_do_link',
        'access callback' => 'user_access',
        'access arguments' => array('admin week4'),
    );
    
    $items['week4/ttest1'] = array(
        'title' => 'Week4 t() test 1',
        'page callback' => 'week4_do_t_test1',
        'access callback' => 'user_access',
        'access arguments' => array('admin week4'),
    );
    
    $items['week4/ttest2'] = array(
        'title' => 'Week4 t() test 2',
        'page callback' => 'week4_do_t_test2',
        'access callback' => 'user_access',
        'access arguments' => array('admin week4'),
    );
    
    $items['week4/ttest3'] = array(
        'title' => 'Week4 t() test 3',
        'page callback' => 'week4_do_t_test3',
        'access callback' => 'user_access',
        'access arguments' => array('admin week4'),
    );
    
    $items['week4/ttest4'] = array(
        'title' => 'Week4 t() test 4',
        'page callback' => 'week4_do_t_test4',
        'access callback' => 'user_access',
        'access arguments' => array('admin week4'),
    );
    
    $items['week4/ttest5'] = array(
        'title' => 'Week4 t() test 5',
        'page callback' => 'week4_do_t_test5',
        'access callback' => 'user_access',
        'access arguments' => array('admin week4'),
    );
    

    return $items;
}


function week4_do($param1 = '')
{

    if ($param1 == '')
        return t('week4');
    
    // this should be passed to t() for sanitation/translation,
    // but I'm using check_plain() for demonstration purposes
    return check_plain($param1);
    
}

function week4_do_link()
{
    return l(t('go here'), 'http://www.brennanmh.com');
}

function week4_do_t_test1()
{
    return t('Here we have the simplest of t() usage. Just a string, no vars, no options.');
}

function week4_do_t_test2($param1 = 'default')
{
    $retval = t('The param from the url: @uparam, would be translated with the string, but if using the exclamation placeholder, !uparamasis would not.', array('@uparam' => $param1,  '!uparamasis' => $param1));
    
    return $retval;
}

function week4_do_t_test3($param1 = 'default')
{
    $retval = t('The param from the url: @uparam, or %uparamem theme emphasized, should have been translated with the rest of this string.', array('@uparam' => $param1,  '%uparamem' => $param1));
    
    return $retval;
}

function week4_do_t_test4()
{
    $retval = t('this string would be translated into spanish, if all was set up properly', array(), array('langcode' => 'es'));
    return $retval;
}

function week4_do_t_test5($param1 = 'default')
{
    $retval = t('The param from the url: @uparam, should have been translated with the rest of this string', array('@uparam' => $param1));

    return $retval;
}

function week4_permission()
{

  return array(
    'week4' => array(
      'title' => t('Week4 Permissions'), 
      'description' => t('Administer week4 permissions'),
    ),
  );

}