<?php

/*
$oauth   = new HTTP_OAuth_Consumer('kmlPL5H7WXD9yQGTKaYLw', 'dfj8BMyc2LIIMJ2mhAHOquKdeyoIZJn7xTqxBkl1uxQ','27013980-zU3ilUFbFtbHsJKpm21Zv5EmIDIjEwKClx1BvO3QA','ONhaSkpZyD3CciBiW4MUN8bhl6OFYJKJIjtj4BdjXgw');
*/
$oauth = new HTTP_OAuth_Consumer('PJkY3Crl1js904GR0vig', '3pAYK4YkcaArpNFv1BQVdrmuhLoIqlWC6jZpyaW3oA', '21955746-cOWCVi5I1ulJKZMG7SxIvA2mMagLKl4kKa8VGtxcY', 'cgs1iaLOVPKJ73J1mvdK2beSko6B5G1r0Emk8h987U4');